// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/file-store @ f5997892f74e7d41028a3c19394e20c38320cdb2
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: file.go
/*
Package filestore owns files: bytes somebody uploaded, under a name, for a
thing that lives in another service. It is the one place on this host a
ticket's attachment, a mail's attachment or a chat's image is kept.

It knows nothing about what a file is attached to and decides nothing about
who may read it. A file is readable exactly when the service that owns the
thing it hangs on says so, and that service is who calls this one: kanban-store
checks the caller's access to the card and then fetches the bytes with the
service token. So this service binds to loopback, takes no call without that
token, and must never be proxied to a browser.
*/

/**
 * File is one upload. See schema.sql for what each field means and why the
 * bytes are not part of it.
 */
export interface File {
  id: string;
  sha256: string;
  size_bytes: number /* int64 */;
  /**
   * ContentType is what the uploader declared, without parameters.
   * DetectedContentType is what the first bytes look like. They differ for an
   * honest reason as often as a dishonest one — a .csv declared text/csv is
   * detected text/plain — so neither is refused; a reader that cares compares.
   */
  content_type: string;
  detected_content_type: string;
  filename: string;
  /**
   * OwnerService and OwnerRef say who put the file here and for what of
   * theirs: "kanban-store" and a card id.
   */
  owner_service: string;
  owner_ref: string;
  /**
   * UploadedByPrincipalID is a principal-store id, or empty. This store
   * checks its shape and not its existence: the calling service has already
   * authenticated that principal, and vouches for it.
   */
  uploaded_by_principal_id?: string;
  created_at: number /* int64 */;
  /**
   * DeletedAt is 0 for a live file. DELETE is reversible and sets it.
   */
  deleted_at?: number /* int64 */;
}
/**
 * Limits is GET /limits: what an upload form must not hardcode.
 */
export interface Limits {
  maximum_file_bytes: number /* int64 */;
  /**
   * InlineContentTypes are the declared types this store will serve for
   * display in a browser when asked to (?inline=true). Every other file is
   * served as a download, whatever was asked.
   */
  inline_content_types: string[];
}
/**
 * Health is GET /health.
 */
export interface Health {
  status: string;
  /**
   * Files counts live rows; Blobs the distinct byte strings they and the
   * deleted rows still name; BlobBytes what those take on disk.
   */
  files: number /* int64 */;
  blobs: number /* int64 */;
  blob_bytes: number /* int64 */;
}
